In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# test
from my_answers import NeuralNetwork
def MSE(y, Y):
    return np.mean((y-Y)**2)



## Unit tests

Run these unit tests to check the correctness of your network implementation. This will help you be sure your network was implemented correctly befor you starting trying to train it. These tests must all be successful to pass the project.

In [3]:
import unittest

inputs = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])
test_w_i_h = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
test_w_h_o = np.array([[0.3],
                       [-0.1]])

class TestMethods(unittest.TestCase):
    
    ##########
    # Unit tests for data loading
    ##########
    
    def test_data_path(self):
        # Test that file path to dataset has been unaltered
        self.assertTrue(data_path.lower() == 'bike-sharing-dataset/hour.csv')
        
    def test_data_loaded(self):
        # Test that data frame loaded
        self.assertTrue(isinstance(rides, pd.DataFrame))
    
    ##########
    # Unit tests for network functionality
    ##########

    def test_activation(self):
        network = NeuralNetwork(3, 2, 1, 0.5)
        # Test that the activation function is a sigmoid
        self.assertTrue(np.all(network.activation_function(0.5) == 1/(1+np.exp(-0.5))))

    def test_train(self):
        # Test that weights are updated correctly on training
        network = NeuralNetwork(3, 2, 1, 0.5)
        network.weights_input_to_hidden = test_w_i_h.copy()
        network.weights_hidden_to_output = test_w_h_o.copy()
        
        network.train(inputs, targets)
        self.assertTrue(np.allclose(network.weights_hidden_to_output, 
                                    np.array([[ 0.37275328], 
                                              [-0.03172939]])))
        self.assertTrue(np.allclose(network.weights_input_to_hidden,
                                    np.array([[ 0.10562014, -0.20185996], 
                                              [0.39775194, 0.50074398], 
                                              [-0.29887597, 0.19962801]])))

    def test_run(self):
        # Test correctness of run method
        network = NeuralNetwork(3, 2, 1, 0.5)
        network.weights_input_to_hidden = test_w_i_h.copy()
        network.weights_hidden_to_output = test_w_h_o.copy()

        self.assertTrue(np.allclose(network.run(inputs), 0.09998924))

suite = unittest.TestLoader().loadTestsFromModule(TestMethods())
unittest.TextTestRunner().run(suite)

FEEFE

Check weights_input_to_hidden 
 [[ 0.63123119  0.25006827]
 [-0.72193852  0.89776456]
 [ 0.16126188 -0.35788317]]
Check weights_hidden_to_output 
 [[-0.21845455]
 [ 0.3823477 ]]
Check weights_input_to_hidden 
 [[-0.71454024  0.74192927]
 [ 0.24951668 -0.04298358]
 [-0.04941163 -0.68925206]]
Check weights_hidden_to_output 
 [[-0.28636164]
 [-1.09786364]]
Check weights_input_to_hidden 
 [[ 0.18298761  0.09944739]
 [ 0.43099356 -0.66288535]
 [-0.57275953 -0.56826026]]
Check weights_hidden_to_output 
 [[0.47841988]
 [0.10451248]]
debug: output_error_term 
 [-0.01870771]
debug: weights_hidden_to_output 
 [[ 0.3 -0.1]]



ERROR: test_data_loaded (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-3-add1f7c23be2>", line 23, in test_data_loaded
    self.assertTrue(isinstance(rides, pd.DataFrame))
NameError: name 'rides' is not defined

ERROR: test_data_path (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-3-add1f7c23be2>", line 19, in test_data_path
    self.assertTrue(data_path.lower() == 'bike-sharing-dataset/hour.csv')
NameError: name 'data_path' is not defined

ERROR: test_train (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-3-add1f7c23be2>", line 40, in test_train
    network.train(inputs, targets)
  File "C:\21\Deep_learning\Git\2020_04_02_Bike_sharing\my_answers.py", line 55, in train
    delta_

<unittest.runner.TextTestResult run=5 errors=3 failures=2>